require 'authority_badger/acts_as_token'
require 'authority_badger/acts_as_token_balance'
require 'authority_badger/acts_as_token_transaction'
require 'authority_badger/acts_as_token_price'
require 'authority_badger/has_tokens'